version: 0.2

env:
  variables:
    build_version: "0.1"

phases:
  install:
    commands:
      - curl -L -O https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      - unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
      - ./sam-installation/install
      - sam --version
  pre_build:
    commands:
      - echo "===== Hello from pre build ===="
  build:
    commands:
      - echo "==== Deploying ===="
      - aws s3 cp s3://lambdas-zips-us-east-1-wk3v4d/hello-world/helloworld.package.yml  template.package.yml
      - |
        sam deploy --template-file template.package.yml \
        --stack-name dev-hello-world \
        --parameter-overrides Env=dev LambdaName=hello-world \
        --capabilities CAPABILITY_IAM
